#!/usr/bin/env python3
"""check_x402_decision_ref.py — the same decision_ref recompute contract as
../decision-ref-recompute/, applied to a real x402 PAYMENT decision, not a
synthetic stand-in.

Fixture: presidio-x402-decision-ref-v1.fixture.json, generated by presidio-hardened-x402
and merged into giskard09/argentum-core#29 (2026-06-30) — the same three vectors
recompute-graded on that PR (autogen#7353, crewAI#4877 threads). This wires the REAL
merged vectors in, replacing the earlier synthetic placeholder this example used.

x402 depth over the base decision-ref-recompute example: here `verdict = f(controls)`,
a precedence-combinator over five recorded control verdicts (pii -> trusted_wallet ->
policy -> replay -> mpa, first-failure-wins), so the ARTIFACT itself is re-derivable from
its own inputs, not just the thin decision_ref wrapper around it. Two hash-level checks
(recompute, tamper-sensitivity) plus two semantic negatives:

  recompute            — decision_ref re-derives byte-for-byte from its own preimage_fields
  tamper-sensitive      — changing any preimage field must move the id
  signer == runtime     — a decision signed by the actor's OWN payment wallet is
                          self-approval, not a second opinion -> fail closed (admission)
  verdict != f(controls) — a recorded verdict that doesn't match its own control set
                          re-derived from scratch is void, regardless of a valid hash
                          -> fail closed (the artifact, not just the wrapper, must recompute)

Zero-dependency, offline. Run: python3 check_x402_decision_ref.py
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Precedence order per the fixture's own f_precedence field: first control that fails
# determines the verdict; MPA required-but-unresolved refers rather than denying.
_PRECEDENCE = ["pii", "trusted_wallet", "policy", "replay", "mpa"]
_PASS_VERDICTS = {
    "pii": {"CLEAN", "PII_REDACTED"},
    "trusted_wallet": {"TRUSTED"},
    "policy": {"ALLOW"},
    "replay": {"FRESH"},
}


def jcs(obj) -> str:
    """RFC 8785-shaped canonicalization: sorted keys, compact separators, raw UTF-8."""
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def sha256_hex(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()


def recompute_artifact_hash(artifact: dict) -> str:
    return sha256_hex(jcs(artifact))


def recompute_decision_ref(preimage_fields: dict, preimage_keys: list[str]) -> str:
    preimage = {k: preimage_fields[k] for k in preimage_keys}
    return sha256_hex(jcs(preimage))


def recompute_verdict(controls: dict) -> str:
    """f(controls): first-failure-wins over the precedence order. Conservative mapping
    for the states this fixture's three vectors actually exercise; a fuller upstream
    verifier would also cover PII_BLOCKED and MPA REQUIRED/REFER paths explicitly."""
    for control in _PRECEDENCE:
        c = controls.get(control, {})
        verdict = c.get("verdict")
        if control == "mpa":
            if c.get("required") and verdict not in ("APPROVED",):
                return "REFER"
            continue
        if verdict not in _PASS_VERDICTS.get(control, set()):
            return "DENY"
    return "ALLOW"


def check_vector(vec: dict) -> bool:
    vid = vec["id"]
    expect = vec["expect"]
    artifact = vec["artifact"]
    print(f"\n--- {vid} (expect: {expect}) ---")
    print(f"  {vec['description'][:100]}...")

    # 1. artifact_hash recomputes from the raw artifact
    got_artifact_hash = recompute_artifact_hash(artifact)
    artifact_hash_ok = got_artifact_hash == vec["artifact_hash"]
    print(f"  artifact_hash recomputes:        {artifact_hash_ok}")

    # 2. decision_ref recomputes from its own published preimage fields
    got_ref = recompute_decision_ref(vec["decision_ref_preimage"], vec["decision_ref_preimage_fields"])
    ref_ok = got_ref == vec["decision_ref"]
    print(f"  decision_ref recomputes:         {ref_ok}")

    # 3. the ARTIFACT's own verdict re-derives from its own controls (not just asserted)
    recomputed_verdict = recompute_verdict(artifact["controls"])
    recorded_verdict = artifact["verdict"]
    verdict_matches = recomputed_verdict == recorded_verdict
    print(f"  f(controls) = {recomputed_verdict:6s} recorded = {recorded_verdict:6s}  match: {verdict_matches}")

    # 4. admission: the signer must not be the actor's own payment wallet (self-approval)
    signer_id = vec["signer"]["key_id"]
    actor_wallet = artifact["actor"]["payment_signer"]
    independent_signer = signer_id != actor_wallet
    print(f"  signer independent of actor:      {independent_signer}  (signer={vec['signer']['resolves_to']})")

    admitted = independent_signer and verdict_matches
    verdict_for_this_vector = "accept" if admitted else "reject"
    passed = verdict_for_this_vector == expect
    print(f"  => {verdict_for_this_vector} (expected {expect}): {'PASS' if passed else 'FAIL'}")
    return artifact_hash_ok and ref_ok and passed


def main() -> int:
    fixture = json.loads((HERE / "presidio-x402-decision-ref-v1.fixture.json").read_text())
    print("=" * 78)
    print("X402 PAYMENT-DECISION RECOMPUTE — real merged fixture, not a synthetic stand-in")
    print(f"source: {fixture['fixture_id']} ({fixture['generated_at']})")
    print("=" * 78)

    all_ok = True
    for vec in fixture["vectors"]:
        all_ok &= check_vector(vec)

    print("\n" + "-" * 78)
    if all_ok:
        print("PASS — all vectors recompute as published; both fail-closed negatives hold.")
        return 0
    print("FAIL — at least one vector did not recompute or admit as expected.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
